"""added background column to Profile model

Revision ID: 8a23d62c4a02
Revises: dd2529197236
Create Date: 2026-08-09 14:43:11.253543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a23d62c4a02'
down_revision: Union[str, Sequence[str], None] = 'dd2529197236'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('background', sa.String(length=256), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'background')
    # ### end Alembic commands ###
