"""added champion_id as a column in the model

Revision ID: dd2529197236
Revises: e9116f2c5743
Create Date: 2026-08-07 17:47:08.265422

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd2529197236'
down_revision: Union[str, Sequence[str], None] = 'e9116f2c5743'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extreme_game', sa.Column('champion_id', sa.String(length=25), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('extreme_game', 'champion_id')
    # ### end Alembic commands ###
